"""Train the SaliNet sensor model (per-analyte Random Forests).

SaliNet learns the inverse of strip colorimetry: given a normalized
reading (rgb_r, rgb_g, rgb_b, temperature_c, humidity_pct) it predicts
salivary analyte concentrations (glucose, CRP, cortisol, sIgA).

DATA PRIORITY — this is the "make it real" path:
  1. REAL DATA. When data/real_training.csv exists (exported from
     GET /api/calibration/export after collecting labeled samples with
     the firmware's calibration mode), each analyte's forest is trained
     on those real samples only.
  2. SYNTHETIC FALLBACK. Analytics without enough real samples fall
     back to the simulated dataset generated by
     generate_synthetic_data.py (Beer-Lambert chemistry + pad
     cross-talk + ADC noise), which keeps a fresh clone trainable and
     keeps determinism for tests.

One forest per analyte is the right architecture for calibration data:
control samples are labeled per analyte, and each forest's feature
importances show exactly which signal drives that analyte.

Random Forest was chosen because it is small, fast, needs no feature
scaling, exposes feature importances (a studyable model), and is
deterministic for a fixed seed.

Train with (from backend/):

    pip install -r requirements.txt
    python scripts/generate_synthetic_data.py      # synthetic fallback
    python scripts/train_model.py

Outputs:
    app/services/model/salinet.joblib   {analyte: RandomForest}
    app/services/model/salinet.json     manifest with per-analyte
                                        metrics + data provenance
"""

from __future__ import annotations

import csv
import datetime
import json
from pathlib import Path

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import joblib

MODEL_NAME = "SaliNet"
MODEL_VERSION = "2.0.0"
SEED = 42

#: Minimum real samples per analyte before it is trusted over synthetic.
MIN_REAL_SAMPLES = 15

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
REAL_DATA_PATH = DATA_DIR / "real_training.csv"
SYNTHETIC_DATA_PATH = DATA_DIR / "sensor_training.csv"
MODEL_DIR = Path(__file__).resolve().parent.parent / "app" / "services" / "model"
MODEL_PATH = MODEL_DIR / "salinet.joblib"
MANIFEST_PATH = MODEL_DIR / "salinet.json"

FEATURES = ["rgb_r", "rgb_g", "rgb_b", "temperature_c", "humidity_pct"]
TARGETS = ["glucose", "crp", "cortisol", "siga"]


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    """Read a CSV (trainer or export format) into raw row dicts."""
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def load_real_data() -> dict[str, tuple[list[list[float]], list[float]]]:
    """Group real calibration rows by analyte.

    Each row carries exactly one labeled concentration (the column for
    that analyte); the other target columns are empty.
    """
    if not REAL_DATA_PATH.exists():
        return {}
    data: dict[str, tuple[list[list[float]], list[float]]] = {
        target: ([], []) for target in TARGETS
    }
    for row in load_csv_rows(REAL_DATA_PATH):
        try:
            features = [float(row[name]) for name in FEATURES]
        except (KeyError, ValueError):
            continue
        for target in TARGETS:
            raw = row.get(target, "").strip()
            if raw:
                data[target][0].append(features)
                data[target][1].append(float(raw))
    return {target: xy for target, xy in data.items() if xy[0]}


def load_synthetic_data() -> dict[str, tuple[list[list[float]], list[float]]]:
    """Load the generated synthetic dataset (all four targets present)."""
    if not SYNTHETIC_DATA_PATH.exists():
        return {}
    rows = load_csv_rows(SYNTHETIC_DATA_PATH)
    data: dict[str, tuple[list[list[float]], list[float]]] = {
        target: ([], []) for target in TARGETS
    }
    for row in rows:
        try:
            features = [float(row[name]) for name in FEATURES]
        except (KeyError, ValueError):
            continue
        for target in TARGETS:
            data[target][0].append(features)
            data[target][1].append(float(row[target]))
    return data


def train_forest(
    features: list[list[float]], targets: list[float]
) -> RandomForestRegressor:
    """Fit one deterministic forest on a single analyte."""
    forest = RandomForestRegressor(
        n_estimators=150,
        max_depth=11,
        min_samples_leaf=8,
        random_state=SEED,
        n_jobs=-1,
    )
    forest.fit(features, targets)
    return forest


def main() -> None:
    real = load_real_data()
    synthetic = load_synthetic_data()

    models: dict[str, RandomForestRegressor] = {}
    metrics: dict[str, dict] = {}
    provenance: dict[str, dict] = {}

    print("training SaliNet v2 (per-analyte forests)")
    for target in TARGETS:
        source = "synthetic"
        if real.get(target) and len(real[target][0]) >= MIN_REAL_SAMPLES:
            X, y = real[target]
            source = "real"
        elif synthetic.get(target):
            X, y = synthetic[target]
        else:
            raise SystemExit(
                f"no training data for '{target}': run "
                "generate_synthetic_data.py or collect calibration samples"
            )

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=SEED
        )
        forest = train_forest(X_train, y_train)
        predictions = forest.predict(X_test)
        r2 = r2_score(y_test, predictions)
        mae = mean_absolute_error(y_test, predictions)

        models[target] = forest
        metrics[target] = {"r2": round(r2, 4), "mae": round(mae, 4)}
        provenance[target] = {
            "source": source,
            "n_samples": len(X),
            "n_real": len(real.get(target, ([], []))[0]) if real.get(target) else 0,
        }
        print(
            f"  {target:10s} source={source:9s} n={len(X):5d}  "
            f"R2={r2:.3f}  MAE={mae:.3f}"
        )

    # Feature importances: average across the four forests.
    print("\nfeature importances (averaged over analyates):")
    importances = [0.0] * len(FEATURES)
    for forest in models.values():
        for i, value in enumerate(forest.feature_importances_):
            importances[i] += value / len(models)
    for name, value in zip(FEATURES, importances):
        print(f"  {name:16s} {value:.3f}")

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    # compress=3: joblib trees are verbose; compression keeps the
    # artifact well under GitHub's 100 MB file limit (~10-15 MB).
    joblib.dump(models, MODEL_PATH, compress=3)

    manifest = {
        "model_name": MODEL_NAME,
        "model_version": MODEL_VERSION,
        "algorithm": "RandomForestRegressor (one forest per analyte)",
        "hyperparameters": {
            "n_estimators": 150,
            "max_depth": 11,
            "min_samples_leaf": 8,
            "random_state": SEED,
        },
        "features": FEATURES,
        "targets": TARGETS,
        "trained_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "provenance": provenance,
        "metrics": metrics,
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"\nsaved model -> {MODEL_PATH}")
    print(f"saved manifest -> {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
