"""Train the SaliNet sensor model (Random Forest, multi-output).

SaliNet learns the inverse of the colorimetric forward model: given a
normalized strip reading (rgb_r, rgb_g, rgb_b, temperature_c,
humidity_pct) it predicts salivary analyte concentrations (glucose,
CRP, cortisol, sIgA). It is trained on synthetic data generated by
generate_synthetic_data.py, which simulates Beer-Lambert chemistry,
pad cross-talk and sensor noise.

The Random Forest was chosen deliberately:

- it is small and fast (a few hundred KB, ms inference);
- it does not need feature scaling;
- it exposes feature importances, so you can see exactly which signal
  each analyte's prediction depends on (a studyable model);
- predictions are deterministic for a fixed seed.

Train with (from backend/):

    pip install -r requirements.txt
    python scripts/generate_synthetic_data.py
    python scripts/train_model.py

Outputs:
    app/services/model/salinet.joblib   the trained forest
    app/services/model/salinet.json     model manifest (features,
                                        targets, metrics, provenance)
"""

from __future__ import annotations

import csv
import datetime
import json
from pathlib import Path

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import joblib

MODEL_NAME = "SaliNet"
MODEL_VERSION = "1.0.0"
SEED = 42

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "sensor_training.csv"
MODEL_DIR = Path(__file__).resolve().parent.parent / "app" / "services" / "model"
MODEL_PATH = MODEL_DIR / "salinet.joblib"
MANIFEST_PATH = MODEL_DIR / "salinet.json"

FEATURES = ["rgb_r", "rgb_g", "rgb_b", "temperature_c", "humidity_pct"]
TARGETS = ["glucose", "crp", "cortisol", "siga"]


def load_data() -> tuple[list[list[float]], list[list[float]]]:
    """Read the generated training CSV into feature/target matrices."""
    if not DATA_PATH.exists():
        raise SystemExit(
            f"{DATA_PATH} not found — run generate_synthetic_data.py first"
        )
    features: list[list[float]] = []
    targets: list[list[float]] = []
    with DATA_PATH.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            features.append([float(row[name]) for name in FEATURES])
            targets.append([float(row[name]) for name in TARGETS])
    return features, targets


def main() -> None:
    features, targets = load_data()
    print(f"loaded {len(features)} samples")

    X_train, X_test, y_train, y_test = train_test_split(
        features, targets, test_size=0.2, random_state=SEED
    )

    forest = RandomForestRegressor(
        n_estimators=200,
        max_depth=12,
        min_samples_leaf=5,
        random_state=SEED,
        n_jobs=-1,
    )
    forest.fit(X_train, y_train)

    predictions = forest.predict(X_test)
    metrics = {}
    print("\nper-analyte metrics (held-out 20%):")
    for i, target in enumerate(TARGETS):
        y_true = [row[i] for row in y_test]
        y_pred = [row[i] for row in predictions]
        r2 = r2_score(y_true, y_pred)
        mae = mean_absolute_error(y_true, y_pred)
        metrics[target] = {"r2": round(r2, 4), "mae": round(mae, 4)}
        print(f"  {target:10s}  R2={r2:.3f}  MAE={mae:.3f}")

    print("\nfeature importances (all targets):")
    for name, importance in zip(FEATURES, forest.feature_importances_):
        print(f"  {name:16s} {importance:.3f}")

    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(forest, MODEL_PATH)

    manifest = {
        "model_name": MODEL_NAME,
        "model_version": MODEL_VERSION,
        "algorithm": "RandomForestRegressor (multi-output)",
        "hyperparameters": forest.get_params(),
        "features": FEATURES,
        "targets": TARGETS,
        "trained_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "data": {
            "source": "scripts/generate_synthetic_data.py",
            "n_samples": len(features),
            "seed": SEED,
        },
        "metrics": metrics,
    }
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    print(f"\nsaved model -> {MODEL_PATH}")
    print(f"saved manifest -> {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
