"""Biomarker analysis pipeline.

Transforms a real device reading (normalized RGB colour channels,
temperature, humidity) plus the user profile into a biomarker report.

Fully deterministic: the same sensor snapshot and profile always produce
the same report. There is no random sampling and no simulated data — a
checkup can only be created from a physical device reading.

The sensor-to-concentration mapping is performed by **SaliNet**, a small
multi-output Random Forest trained on synthetic spectral data generated
from the colorimetric physics below (see ``scripts/generate_synthetic_data.py``
and ``scripts/train_model.py``). When the model artifact is missing
(e.g. a fresh clone), the pipeline falls back to the closed-form
Beer-Lambert calibration constants.

Biology model
-------------
Saliva test strips carry reagent pads. Each pad reacts with one analyte
and develops a coloured chromogen whose intensity follows the
Beer–Lambert law: A = -log10(R / R0), where R is the pad reflectance and
R0 the blank (unstained) reflectance. Concentration is proportional to
absorbance within the linear region of the calibration curve:

    concentration = A * slope

The firmware normalises every raw channel against the sensor's clear
channel, so the values in the API payload are lighting-independent
reflectance proxies in 0..255. A darker pad means a stronger reaction
(colour development absorbs light), hence a higher concentration.

All five analytes below are measurable in saliva with colorimetric
strips (ranges are literature-plausible):

    analyte              signal            unit     ref range
    Salivary Glucose     red pad           mg/dL    0.5 - 7.0   (glucose-oxidase)
    Salivary CRP         blue pad          ng/mL    0.02 - 1.5  (immunochromogenic)
    Salivary Cortisol    green pad         µg/dL    0.1 - 0.6   (ELISA-type, morning)
    Salivary pH          blue/green ratio  pH       6.5 - 7.4   (mixed indicator)
    Secretory IgA        total intensity   mg/dL    5.0 - 25.0  (turbidimetric)

Temperature and humidity corrections follow enzyme-kinetics principles:
reaction rate rises with temperature, and high ambient humidity hydrates
the strip, diluting soluble markers.
"""

from __future__ import annotations

import json
import logging
import math
from functools import lru_cache
from pathlib import Path
from typing import Any

import joblib

logger = logging.getLogger(__name__)

# SaliNet artifact location (generated by scripts/train_model.py).
_MODEL_DIR = Path(__file__).resolve().parent / "model"
_MODEL_PATH = _MODEL_DIR / "salinet.joblib"
_MANIFEST_PATH = _MODEL_DIR / "salinet.json"

# Output order of the SaliNet multi-output forest.
_SALINET_TARGETS = ("glucose", "crp", "cortisol", "siga")

# Reference ranges for each biomarker (name, unit, low, high).
_REFERENCE_RANGES: dict[str, tuple[str, float, float]] = {
    "glucose": ("mg/dL", 0.5, 7.0),
    "crp": ("ng/mL", 0.02, 1.5),
    "cortisol": ("µg/dL", 0.1, 0.6),
    "ph": ("pH", 6.5, 7.4),
    "siga": ("mg/dL", 5.0, 25.0),
}

_RISK_WEIGHTS = {
    "glucose": 0.25,
    "crp": 0.30,
    "cortisol": 0.20,
    "ph": 0.15,
    "siga": 0.10,
}

# Beer-Lambert calibration: concentration per unit absorbance.
_SLOPES: dict[str, float] = {
    "glucose": 15.0,
    "crp": 2.0,
    "cortisol": 1.2,
    "siga": 60.0,
}

# Blank (unstained) pad reflectance: R0 = 0.92.
_BLANK_REFLECTANCE = 0.92

# Linear temperature coefficients (fractional change per °C vs 25 °C).
_TEMP_COEFFS: dict[str, float] = {
    "glucose": 0.010,
    "crp": 0.008,
    "cortisol": 0.006,
    "siga": 0.0,
}

_FRIENDLY_NAMES = {
    "glucose": "Salivary Glucose",
    "crp": "Salivary CRP",
    "cortisol": "Salivary Cortisol",
    "ph": "Salivary pH",
    "siga": "Secretory IgA",
}


def _reflectance(channel: float) -> float:
    """Reflectance proxy from a 0..255 normalized channel (0 = black,
    255 = white). Clamped to keep the logarithm well-defined."""
    value = channel / 255.0
    return min(max(value, 1e-4), 0.999)


def _absorbance(reflectance: float) -> float:
    """Beer-Lambert absorbance: A = -log10(R / R0). Zero for blank pads."""
    return max(0.0, -math.log10(reflectance / _BLANK_REFLECTANCE))


def _beer_lambert_value(
    channel: float, slope: float, temperature_c: float, temp_coeff: float
) -> float:
    """Concentration from a Beer-Lambert fit with a linear temperature
    (enzyme-kinetics) correction."""
    value = _absorbance(_reflectance(channel)) * slope
    return value * (1.0 + temp_coeff * (temperature_c - 25.0))


def _ph_from_ratio(blue: float, green: float) -> float:
    """Salivary pH from the mixed-indicator blue/green reflectance ratio.

    pH = pKa + log10([In-] / [HIn]), and the indicator colour ratio is
    proportional to the deprotonated/protonated form ratio. pKa 7.0
    centred, 1.2 pH units per decade of colour ratio, clamped to the
    physiological range.
    """
    rb, rg = _reflectance(blue), _reflectance(green)
    if rb <= 1e-4 or rg <= 1e-4:
        return 7.0  # both channels dark: ratio undefined, assume neutral
    ratio = rb / rg
    return min(max(7.0 + 1.2 * math.log10(ratio), 5.0), 8.5)


def _load_model() -> dict[str, Any] | None:
    """Load the SaliNet model and manifest, or None when unavailable."""
    if not _MODEL_PATH.exists() or not _MANIFEST_PATH.exists():
        logger.warning(
            "SaliNet model not found (%s); using Beer-Lambert calibration fallback",
            _MODEL_DIR,
        )
        return None
    model = joblib.load(_MODEL_PATH)
    manifest = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
    logger.info(
        "loaded SaliNet %s (%s, %d targets)",
        manifest.get("model_version", "?"),
        manifest.get("algorithm", "?"),
        len(manifest.get("targets", [])),
    )
    return {"model": model, "manifest": manifest}


@lru_cache(maxsize=1)
def _get_model() -> dict[str, Any] | None:
    """Return the process-wide cached SaliNet model (or None)."""
    return _load_model()


def _predict_concentrations(
    sensor_reading: dict[str, Any],
) -> dict[str, float] | None:
    """Predict analyte concentrations with SaliNet.

    Returns None when the model artifact is unavailable, so the caller
    can fall back to the closed-form Beer-Lambert calibration.
    """
    loaded = _get_model()
    if loaded is None:
        return None

    r, g, b = (
        int(sensor_reading.get("rgb_r", 128)),
        int(sensor_reading.get("rgb_g", 128)),
        int(sensor_reading.get("rgb_b", 128)),
    )
    temperature = float(sensor_reading.get("temperature_c", 25.0))
    humidity = float(sensor_reading.get("humidity_pct", 50.0))

    prediction = loaded["model"].predict([[r, g, b, temperature, humidity]])[0]
    return {
        name: float(value) for name, value in zip(_SALINET_TARGETS, prediction)
    }


def _sensor_to_bases(sensor_reading: dict[str, Any]) -> dict[str, float]:
    """Map raw sensor values onto biomarker base values via Beer-Lambert.

    Closed-form fallback used only when the SaliNet model artifact is
    unavailable; SaliNet is trained on data generated from exactly this
    physics (see scripts/generate_synthetic_data.py).
    """
    r, g, b = (
        int(sensor_reading.get("rgb_r", 128)),
        int(sensor_reading.get("rgb_g", 128)),
        int(sensor_reading.get("rgb_b", 128)),
    )
    temperature = float(sensor_reading.get("temperature_c", 25.0))
    humidity = float(sensor_reading.get("humidity_pct", 50.0))

    bases: dict[str, float] = {
        "glucose": _beer_lambert_value(
            r, _SLOPES["glucose"], temperature, _TEMP_COEFFS["glucose"]
        ),
        "crp": _beer_lambert_value(
            b, _SLOPES["crp"], temperature, _TEMP_COEFFS["crp"]
        ),
        "cortisol": _beer_lambert_value(
            g, _SLOPES["cortisol"], temperature, _TEMP_COEFFS["cortisol"]
        ),
        "ph": _ph_from_ratio(b, g),
    }

    # Secretory IgA by turbidimetry: total optical attenuation. High
    # ambient humidity hydrates the pad and dilutes the soluble marker.
    average_intensity = (r + g + b) / 3.0
    bases["siga"] = _beer_lambert_value(
        average_intensity, _SLOPES["siga"], temperature, _TEMP_COEFFS["siga"]
    ) * (1.0 - 0.002 * (humidity - 50.0))

    return bases


def _profile_adjustments(profile: dict[str, Any]) -> dict[str, float]:
    """Compute deterministic biomarker adjustments from the user profile.

    - Older age and higher BMI raise salivary glucose and CRP (metabolic
      physiology: insulin resistance drives both).
    - Higher activity level raises secretory IgA (exercise bolsters
      mucosal immunity; overtraining at athlete level blunts it).
    """
    deltas: dict[str, float] = {}
    age = int(profile.get("age", 35))
    activity = profile.get("activity_level", "moderate")
    height_cm = float(profile.get("height_cm", 170))
    weight_kg = float(profile.get("weight_kg", 70))
    bmi = weight_kg / ((height_cm / 100) ** 2) if height_cm > 0 else 22.0

    deltas["glucose"] = max(0, (age - 50)) * 0.006 + max(0, bmi - 25) * 0.02
    deltas["crp"] = max(0, (age - 50)) * 0.005

    siga_deltas = {
        "sedentary": -2.0,
        "light": 1.0,
        "moderate": 2.0,
        "active": 3.0,
        "athlete": 1.0,  # overtraining dip
    }
    deltas["siga"] = siga_deltas.get(activity, 0.0)

    return deltas


def _state_for(value: float, ref_low: float, ref_high: float) -> str:
    """Classify a value against its reference range."""
    if value < ref_low:
        return "low"
    if value > ref_high:
        return "high"
    return "normal"


def _build_biomarker(key: str, value: float) -> dict[str, Any]:
    """Build the public biomarker record with a human-friendly message."""
    unit, ref_low, ref_high = _REFERENCE_RANGES[key]
    state = _state_for(value, ref_low, ref_high)
    name = _FRIENDLY_NAMES[key]

    state_messages = {
        "low": f"{name} is below the reference range. "
        f"Consider reviewing your diet or speaking with a clinician.",
        "normal": f"{name} is within the reference range. Keep it up!",
        "high": f"{name} is above the reference range. "
        f"Consider a follow-up conversation with a clinician.",
    }

    return {
        "name": name,
        "value": round(value, 2),
        "unit": unit,
        "ref_low": ref_low,
        "ref_high": ref_high,
        "state": state,
        "message": state_messages[state],
    }


def generate_report(
    profile: dict[str, Any],
    sensor_reading: dict[str, Any],
) -> dict[str, Any]:
    """Generate a deterministic report from a real device reading.

    Args:
        profile: User fields (age, sex, height_cm, weight_kg, activity_level).
        sensor_reading: Raw device snapshot (rgb_r, rgb_g, rgb_b,
            temperature_c, humidity_pct). Required — the report is always
            derived from physical sensor data.

    Returns:
        Dict with ``overall_risk``, ``summary``, ``text_summary`` and
        ``biomarkers``.
    """
    if not sensor_reading:
        raise ValueError("sensor_reading is required to generate a report")

    bases = _predict_concentrations(sensor_reading)
    if bases is None:
        # SaliNet artifact missing (fresh clone): closed-form chemistry.
        bases = _sensor_to_bases(sensor_reading)
    else:
        # pH is a ratio measurement (mixed indicator), not a
        # concentration: it stays on the closed-form chemistry.
        bases["ph"] = _ph_from_ratio(
            int(sensor_reading.get("rgb_b", 128)),
            int(sensor_reading.get("rgb_g", 128)),
        )
    deltas = _profile_adjustments(profile)

    biomarkers = []
    for key, (unit, ref_low, ref_high) in _REFERENCE_RANGES.items():
        value = bases[key] + deltas.get(key, 0.0)
        if key == "ph":
            value = min(max(value, 5.0), 8.5)
        else:
            value = max(ref_low * 0.4, min(ref_high * 1.6, value))
        biomarkers.append(_build_biomarker(key, value))

    # Weighted risk score: each out-of-range marker contributes its weight.
    score = 0.0
    for key, marker in zip(_REFERENCE_RANGES, biomarkers):
        if marker["state"] != "normal":
            score += _RISK_WEIGHTS[key]

    if score >= 0.45:
        overall_risk = "high"
    elif score >= 0.2:
        overall_risk = "medium"
    else:
        overall_risk = "low"

    out_of_range = [
        f"{m['name']} ({m['state']})" for m in biomarkers if m["state"] != "normal"
    ]
    if out_of_range:
        text_summary = (
            "Analysis based on your latest Doctordrobe device reading. "
            f"Overall risk: {overall_risk.upper()}. "
            f"Attention needed on: {', '.join(out_of_range)}."
        )
    else:
        text_summary = (
            "Analysis based on your latest Doctordrobe device reading. "
            f"Overall risk: {overall_risk.upper()}. "
            "All markers are within their reference ranges. "
            "Continue your healthy routine and check again tomorrow."
        )

    summary = (
        f"Device reading · Overall risk {overall_risk.upper()} · "
        f"{len([m for m in biomarkers if m['state'] != 'normal'])} marker(s) out of range"
    )

    return {
        "overall_risk": overall_risk,
        "summary": summary,
        "text_summary": text_summary,
        "biomarkers": biomarkers,
    }
